name: Package Push Nuget
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  package-build:
    name: package build and push
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v2

    - name: run a one-line script
      run: env

    - name: setting dotnet version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          2.1.x
          2.2.x
          3.0.x
          3.1.x
          5.0.x
          6.0.x
          7.0.x
          8.0.x
        include-prerelease: true

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build -c Release --no-restore /p:ContinuousIntegrationBuild=true

    - name: pack
      run: dotnet pack -c Release --output ./nupkg --include-symbols -p:PackageVersion=$GITHUB_REF_NAME

    - name: ls
      run: ls -R ./nupkg

    - name: package push
      run: dotnet nuget push "./nupkg/*.symbols.nupkg" --skip-duplicate -k  ${{secrets.NUGET_TOKEN}}  -s https://api.nuget.org/v3/index.json
